//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Albert_Einstein_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string sexo { get; set; }
        public string codigoPostal { get; set; }
        public string tipoUtilizador { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
